"""Extended settings panel with vision generation controls."""
from __future__ import annotations

from PySide6.QtCore import Signal
from PySide6.QtWidgets import QDoubleSpinBox, QFormLayout, QGroupBox, QPushButton, QSpinBox

from engine.models import AppSettings
from ui.settings import SettingsPanel as BaseSettingsPanel


DEFAULT_MAX_TOKENS = 576
DEFAULT_MIN_SUBJECT_PERCENT = 10.0
DEFAULT_TARGET_SUBJECT_PERCENT = 15.0


class SettingsPanel(BaseSettingsPanel):
    """Base settings panel plus persisted generation and mosaic preview controls."""

    preview_requested = Signal()
    open_folder_requested = Signal()

    def __init__(self, settings: AppSettings, parent=None) -> None:
        super().__init__(settings, parent)
        self._add_max_tokens_control()
        self._max_tokens_spin.setValue(
            max(64, min(4096, int(getattr(settings, "max_tokens", DEFAULT_MAX_TOKENS))))
        )
        self._max_tokens_spin.valueChanged.connect(self._on_max_tokens_changed)
        self._add_subject_size_controls(settings)
        self._add_preview_control()
        self._add_open_folder_control()

    def _add_max_tokens_control(self) -> None:
        inference_group = next(
            (group for group in self.findChildren(QGroupBox) if group.title() == "Inference"),
            None,
        )
        if inference_group is None or not isinstance(inference_group.layout(), QFormLayout):
            raise RuntimeError("Could not locate Inference settings form.")

        self._max_tokens_spin = QSpinBox()
        self._max_tokens_spin.setRange(64, 4096)
        self._max_tokens_spin.setSingleStep(32)
        self._max_tokens_spin.setSuffix(" tokens")
        self._max_tokens_spin.setToolTip(
            "Maximum tokens generated by the vision model. 576 recommended for image analysis."
        )
        inference_group.layout().addRow("Max Tokens:", self._max_tokens_spin)

    def _add_subject_size_controls(self, settings: AppSettings) -> None:
        mosaic_group = next(
            (group for group in self.findChildren(QGroupBox) if group.title() == "Mosaic"),
            None,
        )
        if mosaic_group is None or not isinstance(mosaic_group.layout(), QFormLayout):
            raise RuntimeError("Could not locate Mosaic settings form.")

        self._min_subject_percent_spin = QDoubleSpinBox()
        self._min_subject_percent_spin.setRange(1.0, 50.0)
        self._min_subject_percent_spin.setSingleStep(1.0)
        self._min_subject_percent_spin.setDecimals(1)
        self._min_subject_percent_spin.setSuffix(" % of canvas H")
        self._min_subject_percent_spin.setToolTip(
            "Minimum visible person height allowed in the generated mosaic, as a percentage of canvas height."
        )

        self._target_subject_percent_spin = QDoubleSpinBox()
        self._target_subject_percent_spin.setRange(1.0, 75.0)
        self._target_subject_percent_spin.setSingleStep(1.0)
        self._target_subject_percent_spin.setDecimals(1)
        self._target_subject_percent_spin.setSuffix(" % of canvas H")
        self._target_subject_percent_spin.setToolTip(
            "Preferred visible person height used when evaluating mosaic readability, as a percentage of canvas height."
        )

        min_value = max(
            1.0,
            min(50.0, float(getattr(settings, "min_subject_percent", DEFAULT_MIN_SUBJECT_PERCENT))),
        )
        target_value = max(
            min_value,
            min(75.0, float(getattr(settings, "target_subject_percent", DEFAULT_TARGET_SUBJECT_PERCENT))),
        )
        self._min_subject_percent_spin.setValue(min_value)
        self._target_subject_percent_spin.setValue(target_value)
        self._min_subject_percent_spin.valueChanged.connect(self._on_subject_size_changed)
        self._target_subject_percent_spin.valueChanged.connect(self._on_subject_size_changed)

        mosaic_group.layout().addRow("Min Subject Size:", self._min_subject_percent_spin)
        mosaic_group.layout().addRow("Target Subject Size:", self._target_subject_percent_spin)

    def _add_preview_control(self) -> None:
        actions_group = next(
            (group for group in self.findChildren(QGroupBox) if group.title() == "Actions"),
            None,
        )
        if actions_group is None or actions_group.layout() is None:
            raise RuntimeError("Could not locate Actions settings group.")

        self._btn_preview = QPushButton("👁  Preview")
        self._btn_preview.setObjectName("preview_btn")
        self._btn_preview.setEnabled(False)
        self._btn_preview.setToolTip("Open an interactive canvas showing the generated mosaic layout.")
        self._btn_preview.clicked.connect(self.preview_requested.emit)
        actions_group.layout().addWidget(self._btn_preview)

    def _add_open_folder_control(self) -> None:
        actions_group = next(
            (group for group in self.findChildren(QGroupBox) if group.title() == "Actions"),
            None,
        )
        if actions_group is None or actions_group.layout() is None:
            raise RuntimeError("Could not locate Actions settings group.")

        self._btn_open_folder = QPushButton("📂  Open Folder")
        self._btn_open_folder.setToolTip(
            "Open an image folder and load its existing cache without starting model analysis."
        )
        self._btn_open_folder.clicked.connect(self.open_folder_requested.emit)
        actions_group.layout().insertWidget(0, self._btn_open_folder)

    def set_preview_enabled(self, enabled: bool) -> None:
        self._btn_preview.setEnabled(bool(enabled))

    def _on_changed(self, *args) -> None:
        if not self._building:
            self.set_preview_enabled(False)
        super()._on_changed(*args)

    def current_settings(self) -> AppSettings:
        settings = super().current_settings()
        settings.max_tokens = self._max_tokens_spin.value()
        settings.min_subject_percent = self._min_subject_percent_spin.value()
        settings.target_subject_percent = max(
            settings.min_subject_percent,
            self._target_subject_percent_spin.value(),
        )
        return settings

    def _on_max_tokens_changed(self, *_args) -> None:
        if not self._building:
            self.set_preview_enabled(False)
            self.settings_changed.emit(self.current_settings())

    def _on_subject_size_changed(self, *_args) -> None:
        if not self._building:
            min_value = self._min_subject_percent_spin.value()
            if self._target_subject_percent_spin.value() < min_value:
                self._target_subject_percent_spin.blockSignals(True)
                self._target_subject_percent_spin.setValue(min_value)
                self._target_subject_percent_spin.blockSignals(False)
            self.set_preview_enabled(False)
            self.settings_changed.emit(self.current_settings())

    def set_source_folder(self, folder: str) -> None:
        """Update the visible source folder without triggering a settings event."""
        self._building = True
        self._folder_edit.setText(folder)
        self._building = False
