"""Extended settings panel with vision generation controls."""
from __future__ import annotations

from PySide6.QtWidgets import QFormLayout, QGroupBox, QSpinBox

from engine.models import AppSettings
from ui.settings import SettingsPanel as BaseSettingsPanel


DEFAULT_MAX_TOKENS = 576


class SettingsPanel(BaseSettingsPanel):
    """Base settings panel plus persisted Max Tokens control."""

    def __init__(self, settings: AppSettings, parent=None) -> None:
        super().__init__(settings, parent)
        self._add_max_tokens_control()
        self._max_tokens_spin.setValue(
            max(64, min(4096, int(getattr(settings, "max_tokens", DEFAULT_MAX_TOKENS))))
        )
        self._max_tokens_spin.valueChanged.connect(self._on_max_tokens_changed)

    def _add_max_tokens_control(self) -> None:
        inference_group = next(
            (group for group in self.findChildren(QGroupBox) if group.title() == "Inference"),
            None,
        )
        if inference_group is None or not isinstance(inference_group.layout(), QFormLayout):
            raise RuntimeError("Could not locate Inference settings form.")

        self._max_tokens_spin = QSpinBox()
        self._max_tokens_spin.setRange(64, 4096)
        self._max_tokens_spin.setSingleStep(32)
        self._max_tokens_spin.setSuffix(" tokens")
        self._max_tokens_spin.setToolTip(
            "Maximum tokens generated by the vision model. 576 recommended for image analysis."
        )
        inference_group.layout().addRow("Max Tokens:", self._max_tokens_spin)

    def current_settings(self) -> AppSettings:
        settings = super().current_settings()
        settings.max_tokens = self._max_tokens_spin.value()
        return settings

    def _on_max_tokens_changed(self, *_args) -> None:
        if not self._building:
            self.settings_changed.emit(self.current_settings())
